name: carnd-lenet-lab
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - pip:
        - tensorflow